spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: senha
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
  H2:
    console:
      enabled: true
      path: /h2-console
